// Generated by scripts/generate-blur.mjs. Do not edit by hand.
// Regenerate after replacing the source image.

export const meBlurDataURL = "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoIAAoAA4BaJYgCdADZTftgAP3iXv6M+Djd4e4schMzpzxgYhlVtOB2AkfbQUZ+1A0pM03N5i2WXgAA";
