#!/usr/bin/env node
/**
 * Regenerates src/lib/blur.ts from public/me.webp.
 * Run manually after the portrait changes:
 *   node scripts/generate-blur.mjs
 *
 * sharp is provided transitively by next, so no new devDep is needed.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const inputPath = resolve(root, 'public/me.webp');
const outputPath = resolve(root, 'src/lib/blur.ts');

const TARGETS = [{ name: 'me', input: inputPath, width: 8 }];

const lines = [
  '// Generated by scripts/generate-blur.mjs. Do not edit by hand.',
  '// Regenerate after replacing the source image.',
  '',
];

for (const target of TARGETS) {
  const buffer = await readFile(target.input);
  const meta = await sharp(buffer).metadata();
  const aspect = meta.width && meta.height ? meta.height / meta.width : 1;
  const height = Math.max(1, Math.round(target.width * aspect));

  const blurred = await sharp(buffer)
    .resize(target.width, height, { fit: 'inside' })
    .webp({ quality: 40 })
    .toBuffer();

  const dataUrl = `data:image/webp;base64,${blurred.toString('base64')}`;
  const constName = `${target.name}BlurDataURL`;
  lines.push(`export const ${constName} = ${JSON.stringify(dataUrl)};`);
}

lines.push('');
await writeFile(outputPath, lines.join('\n'), 'utf8');
console.log(`wrote ${outputPath}`);
